server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin
  application:
    name: RealTimeChatGateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: http://localhost:8082/order-service
          predicates:
            - Path=/orders/**
